sudo: false

language: scala

scala:
   - 2.11.11
   - 2.12.4

branches:
    - master
    - develop

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

jdk:
  - oraclejdk8

services:
  - docker

script:
  # run kafka for integration tests
  - docker run -p 9092:9092 -p 2181:2181 --env ADVERTISED_HOST=$(hostname) --env ADVERTISED_PORT=9092 -d spotify/kafka
  - sbt clean coverage test it:test

after_success:
  - sbt coverageReport coveralls

notifications:
  email:
    recipients:
      - vladimir@dokwork.ru
